name: Deploy Site

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  set-deploy-type:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: get deployment target
        run: |
          TARGET=$(cat DEPLOY_STRATEGY)
          echo "TARGET=$TARGET" >> $GITHUB_ENV

      - name: check if target is valid
        if: success() && !contains(fromJSON('["gh-pages", "firebase", "none"]'), env.TARGET)
        run: echo 'Invalid Deployment Target' && exit 1

      - name: set output to deploy target
        id: set-output
        run: echo "::set-output name=target::${{ env.TARGET }}"

  deploy-none:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'none'
    steps:
      - run: echo 'No Deployment Specified' && exit 0

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'gh-pages'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: set-deploy-type
    if: needs.set-deploy-type.outputs.target == 'firebase'
    steps:
      - uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: build jekyll
        run: |
          bundle install
          bundle exec jekyll build

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
